<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LPT-E580-LPT77" ignored="0" name="Test1" tests="4" failures="1" timestamp="2021-03-02T18:57:39 IST" time="79.019" errors="0">
  <testcase name="Itry" time="24.461" classname="testSuite.Functional">
    <skipped/>
  </testcase> <!-- Itry -->
  <testcase name="Itry" time="21.499" classname="testSuite.Functional">
    <skipped/>
  </testcase> <!-- Itry -->
  <testcase name="Itry" time="21.56" classname="testSuite.Functional">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:92)
at org.junit.Assert.fail(Assert.java:100)
at testSuite.Functional.Itry(Functional.java:69)
at java.util.ArrayList.forEach(ArrayList.java:1257)
... Removed 27 stack frames]]>
    </failure>
  </testcase> <!-- Itry -->
  <testcase name="Test01" time="0.002" classname="testSuite.Functional"/>
</testsuite> <!-- Test1 -->
